version: '3.8'
services:
  postgres:
    image: "postgres:12-alpine"
    container_name: "postgres-1"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "root"
    volumes:
      - "/Users/motaufiqurohman/docker-mount/posgres_12-alpine:/var/lib/postgresql/data"
    networks:
      - app_network
    restart: on-failure

  redis:
    image: "redis:6.2.6-alpine3.15"
    container_name: "redis-1"
    ports:
      - "6379:6379"
    networks:
      - app_network
    restart: on-failure

  app:
    image: go-app:latest
    container_name: "go-app-1"
    ports:
      - "8080:8080"
    environment:
      - ENV=env-production.env
    volumes:
      - "/Users/motaufiqurohman/go/src/taufiq.code/golang-base-code/logs:/app/logs"
    networks:
      - app_network
    restart: on-failure

networks:
  app_network:
    name: "go-app-network"
